### ISSUE TITLE
OpenCorpora.ort

### ISSUE THREAD

**Issue by SecNotice** [igor-shevchenko/rutermextract#3]
В [статье rutermextract 0.3](https://pypi.python.org/pypi/rutermextract)  Вами указано, что 
> К сожалению, на данный момент это единственный возможный вариант, поскольку для русского языка не существует открытого синтаксического корпуса, который можно использовать для обучения синтаксических моделей.

Рассматривали ли Вы проект [opencorpora.org](http://opencorpora.org/)? 
Какие препятствия на пути его использования Вы видите?

**Comment by igor-shevchenko** [comment]
@SecNotice rutermextract зависит от библиотеки [pymorphy2](https://github.com/kmike/pymorphy2), которая использует морфологические данные из OpenCorpora, так что в принципе этот корпус используется. Эти данные позволяют анализировать слова по отдельности, чтобы определять для слова, например, часть речи или падеж. Но чтобы натренировать модель, основанную на машинном обучении, нам нужен корпус, где размечены именные группы. Это уже информация о связях между словами в предложении, и в Открытом корпусе ее вроде бы нет.

Возможно, за последнее время что-то изменилось и появились какие-то новые доступные данные.  Если это так, то, пожалуйста, дайте мне знать.

**Comment by alex1910hello** [comment]
а синтаксически размеченный корпус — СинТагРус почему не стали рассматривать для обучения модели на машинном обучении?

**Comment by igor-shevchenko** [comment]
@alex1910hello а он есть в открытом доступе?

**Comment by alex1910hello** [comment]
http://www.ruscorpora.ru/corpora-usage.html

**Comment by igor-shevchenko** [comment]
@alex1910 требования лицензии не совсем понятные. Кажется, даже если я получу доступ к корпусу, распространять обученную на нем модель будет нельзя.

Но зато этот корпус можно было бы неплохо использовать для оценки качества правил, по которым извлекаются ключевые слова. Тогда добавлять новые правила будет легче.

**Comment by alex1910hello** [comment]
а зачем в регулярном выражении r'([^\w]*(?:\s|^|$)+[^\w]*)' вот это правило (?:\s|^|$)? в русском языке встречается символ ^?

**Comment by SecNotice** [comment]
@alex1910hello Он же не экранированный - тогда это "начало строки" в регулярках.

**Comment by alex1910hello** [comment]
@SecNotice это понятно. меня интересует назанчение его в этом правиле  (?:\s|^|$). и еще знак доллара непонятен.

**Comment by SecNotice** [comment]
@alex1910hello Для отладки регулярок очень хорош сайт https://regex101.com/
Введите непонятное выражение туда, оно будет разобрано и показано - какая его часть за что отвечает.

**Comment by alex1910hello** [comment]
@igor-shevchenko зачем класс Normalizer? разве нормализация токенов не проводилась pymorphy при помощи функции inflect()?

**Comment by igor-shevchenko** [comment]
@alex1910hello да, нормализация происходит с помощью функции `inflect` из pymorphy. `Normalizer` как раз ее и вызывает. Еще он содержит логику для нормализации тёрмов из нескольких слов.

Думаю, проще всего понять, что делает этот класс, посмотрев на [исходник](https://github.com/igor-shevchenko/rutermextract/blob/master/rutermextract/normalizer.py).

**Comment by igor-shevchenko** [comment]
Закрываю этот issue, потому что обсуждение здесь уже сильно отклонилось от изначального вопроса. Но если есть еще какие-то вопросы по коду, спрашивайте.

**Comment by alex1910hello** [comment]
а как добавить метрику cvalue для вычисления статистики слов?

**Comment by igor-shevchenko** [comment]
@alex1910hello а что это такое? Можете немного подробнее пояснить?

**Comment by alex1910hello** [comment]
@igor-shevchenko http://www.dialog-21.ru/digests/dialog2008/materials/html/11.htm

**Comment by igor-shevchenko** [comment]
@alex1910hello можно реализовать эту метрику как функцию, принимающую `Term`. Ее можно передать в параметре `weight`. [Пример](weight)

**Comment by alex1910hello** [comment]
а частота встречаемости слов вычисляется для всех слов, которые выделены с использованием заданных правил?

**Comment by igor-shevchenko** [comment]
@alex1910hello да, для всех.

**Comment by igor-shevchenko** [comment]
@alex1910hello покажите код, о котором идет речь.

**Comment by alex1910hello** [comment]
В коде labeler.py хочу в цикле на итерации брать word  и следующее слово за ним. Вот как указывается следующее слово ?

**Comment by alex1910hello** [comment]
for word in words:
            if not word:
                # Если не удалось отпарсить, то сбрасываем.
                while number_of_adj:
                    yield 'O'
                    number_of_adj -= 1 
                    ......



Думал, что дующее слово после  word можно взять вот так words[i+1], но по words нельзя иттерироваться(
как быть?

**Comment by SecNotice** [comment]
Может быть, поможет этот трюк: 
https://stackoverflow.com/questions/1011938/python-previous-and-next-values-inside-a-loop#1012089

**Comment by alex1910hello** [comment]
А какая вычислительная сложность у этой процедуры выделения ?

**Comment by igor-shevchenko** [comment]
@alex1910hello выглядит как что-то вроде O(mn+n²) в худшем случае, где n — количество слов в тексте, m — сложность парсинга в pymorphy. Но это не точно.

**Comment by alex1910hello** [comment]
получается у вашего извлечения линейная зависимость количества выделенных слов от объема  всего текста?

**Comment by igor-shevchenko** [comment]
@alex1910hello в реальности да, формально — квадратичная или даже еще хуже.

**Comment by alex1910hello** [comment]
мда, если не ставить лимит на колисетво слов, то конечно ужас как много их получается
