### ISSUE TITLE
Не "разрывать" пары Имя Фамилия

### ISSUE THREAD

**Issue by bigbadmytyx** [igor-shevchenko/rutermextract#7]
Добрый день, 
благодарю вас за отличную библиотеку, есть одна небольшая проблема/вопрос.

Фраза:

> Украина с 00:00 понедельника перешла на карантинные ограничения, которые действовали в стране до 8 января, сообщил министр здравоохранения Максим Степанов в ходе пресс-брифинга в Киеве в понедельник.

При разбивке на ключевые слова вернет:
понедельник 2
ход пресс-брифинга 1
министр здравоохранения 1
карантинные ограничения 1
8 января 1
украина 1
страна 1
степанов 1
максим 1
киев 1

Можно ли как-то сохранить имя фамилию одним ключевым словом, например  Максим Степанов , а не отдельными словами максим  и степанов ?

**Comment by igor-shevchenko** [comment]
Добрый день! 

Я сейчас сам библиотеку уже не дорабатываю, но идея хорошая. В pymorphy есть теги, позволяющие определять имена и фамилии, так что реализовать это возможно. Если пришлете пул-реквест с реализацией и тестом — приму его и опубликую новую версию.

**Comment by bigbadmytyx** [comment]
@igor-shevchenko спасибо, постараюсь разобраться и сделаю пул-реквест
